title                         : Sapicore Documentation
author                        : Roy Moyal, Jeremy Forest, Matthew Einhorn, Ayon Borthakur, Thomas Cleland
logo                          : images/cpl_logo.png
project                       : Sapicore
copyright                     : 2022, Computational Physiology Lab, Cornell University
version                       : 0.3.1

execute:
  execute_notebooks           : auto

repository:
  #TODO Uncomment once repo is public
  url: https://github.com/cplab/sapicore
  path_to_book: docs/book

html:
  home_page_in_navbar         : true
  use_edit_page_button        : true
  use_repository_button       : true
  use_issue_button            : true
  # path_to_docs: "../../docs/"

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

sphinx:
  extra_extensions:
  - "sphinx.ext.autodoc"
  - "sphinx.ext.autosummary"
  - "sphinx.ext.doctest"
  - "sphinx.ext.napoleon"
  - "sphinx_rtd_theme"
  - 'sphinx.ext.intersphinx'
  - 'sphinx.ext.viewcode'
  - 'sphinx_copybutton'
  config:
    autosummary_generate: true
    templates_path:
    - "../source/_templates"
